### PR TITLE
make Julia 0.5 compatible

### PR DESCRIPTION
**Pull request by tanmaykm**
- uses Compat.jl to make this Julia 0.5 compatible
- minor typo fixes on README.md
- add Julia 0.4 to travis test matrix

### CODE REVIEW

**Comment by tanmaykm** [comment]
travis test failures on Julia nightlies seem unrelated to this PR

**Comment by tanmaykm** [comment]
@sorpaas Now that https://github.com/sorpaas/HPack.jl/pull/2 is passing on Julia nightlies, even this PR should too.

Could you please trigger the travis tests again?

**Comment by sorpaas** [comment]
Yeah it passed! Thanks!

**Comment by tkelman** [comment]
Did you forget to add a Compat import and REQUIRE line here?

**Comment by tanmaykm** [comment]
Hmm... It doesn't seem to need `Compat` for 0.5 and I probably copied and edited the PR text from https://github.com/sorpaas/HPack.jl/pull/2 incompletely. Thanks for pointing it out.

But it does need it for 0.6. So I may make another PR, unless someone else gets to it earlier.

**Pull request merged**
